from sqlalchemy import Column, Integer, String, Date, Numeric
from sqlalchemy.orm import synonym
from .database import Base

class Transaction(Base):
    """
    SQLAlchemy Model representing the 'transactions' table in PostgreSQL.
    Contains all 79 CAMS/Karvy fields.
    """
    __tablename__ = "transactions"

    id = Column(Integer, primary_key=True, index=True)
    amc_code = Column(String, nullable=True)
    folio_no = Column(String, nullable=True)
    prodcode = Column(String, nullable=True)
    scheme = Column(String, nullable=True, index=True)
    inv_name = Column(String, nullable=True)
    trxntype = Column(String, nullable=True)
    trxnno = Column(String, nullable=True)
    trxnmode = Column(String, nullable=True)
    trxnstat = Column(String, nullable=True)
    usercode = Column(String, nullable=True)
    usrtrxno = Column(String, nullable=True)
    traddate = Column(Date, nullable=True, index=True)
    postdate = Column(Date, nullable=True)
    purprice = Column(Numeric(15, 4), nullable=True)
    units = Column(Numeric(15, 4), nullable=True)
    amount = Column(Numeric(15, 2), nullable=True)
    brokcode = Column(String, nullable=True)
    subbrok = Column(String, nullable=True)
    brokperc = Column(Numeric(10, 4), nullable=True)
    brokcomm = Column(Numeric(15, 2), nullable=True)
    altfolio = Column(String, nullable=True)
    rep_date = Column(String, nullable=True)
    time1 = Column(String, nullable=True)
    trxnsubtyp = Column(String, nullable=True)
    application_no = Column(String, nullable=True)
    trxn_nature = Column(String, nullable=True)
    tax = Column(Numeric(15, 2), nullable=True)
    total_tax = Column(Numeric(15, 2), nullable=True)
    te_15h = Column(String, nullable=True)
    micr_no = Column(String, nullable=True)
    remarks = Column(String, nullable=True)
    swflag = Column(String, nullable=True)
    old_folio = Column(String, nullable=True)
    seq_no = Column(String, nullable=True)
    reinvest_flag = Column(String, nullable=True)
    mult_brok = Column(String, nullable=True)
    stt = Column(Numeric(15, 2), nullable=True)
    location = Column(String, nullable=True)
    scheme_type = Column(String, nullable=True)
    tax_status = Column(String, nullable=True)
    load = Column(Numeric(15, 2), nullable=True)
    scanrefno = Column(String, nullable=True)
    pan = Column(String, nullable=True, index=True)
    inv_iin = Column(String, nullable=True)
    targ_src_scheme = Column(String, nullable=True)
    trxn_type_flag = Column(String, nullable=True)
    ticob_trtype = Column(String, nullable=True)
    ticob_trno = Column(String, nullable=True)
    ticob_posted_date = Column(String, nullable=True)
    dp_id = Column(String, nullable=True)
    trxn_charges = Column(Numeric(15, 2), nullable=True)
    eligib_amt = Column(Numeric(15, 2), nullable=True)
    src_of_txn = Column(String, nullable=True)
    trxn_suffix = Column(String, nullable=True)
    siptrxnno = Column(String, nullable=True)
    ter_location = Column(String, nullable=True)
    euin = Column(String, nullable=True)
    euin_valid = Column(String, nullable=True)
    euin_opted = Column(String, nullable=True)
    sub_brk_arn = Column(String, nullable=True)
    exch_dc_flag = Column(String, nullable=True)
    src_brk_code = Column(String, nullable=True)
    sys_regn_date = Column(String, nullable=True)
    ac_no = Column(String, nullable=True)
    bank_name = Column(String, nullable=True)
    reversal_code = Column(String, nullable=True)
    exchange_flag = Column(String, nullable=True)
    ca_initiated_date = Column(String, nullable=True)
    gst_state_code = Column(String, nullable=True)
    igst_amount = Column(Numeric(15, 2), nullable=True)
    cgst_amount = Column(Numeric(15, 2), nullable=True)
    sgst_amount = Column(Numeric(15, 2), nullable=True)
    rev_remark = Column(String, nullable=True)
    original_trxnno = Column(String, nullable=True)
    stamp_duty = Column(Numeric(15, 2), nullable=True)
    folio_old = Column(String, nullable=True)
    scheme_folio_number = Column(String, nullable=True)
    amc_ref_no = Column(String, nullable=True)
    request_ref_no = Column(String, nullable=True)

    # Synonyms for backwards compatibility
    investor_name = synonym("inv_name")
    pan_number = synonym("pan")
    mutual_fund_name = synonym("scheme")
    transaction_date = synonym("traddate")
    purchase_amount = synonym("amount")
    nav_units = synonym("units")
    nav_price = synonym("purprice")
